<?php

use controller\CollectionController\CollectionController\CollectionController;

include_once "../controller/CollectionController.php";
// session_start();

$collection = new CollectionController();

$from_date = date("Y-m-d", strtotime($_POST['from_date']));
$end_date = date("Y-m-d", strtotime($_POST['end_date']));
$field = $_POST['field'];
$center = $_POST['center'];
$period = $_POST['period'];
$officer = $_POST['officer'];

if ($field == null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.center_id= ${center} AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.center_id= ${center} AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.center_id= ${center} AND l.officers_id = ${officer} AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.center_id= ${center} AND lw.officers_id = ${officer} AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period != null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.center_id= ${center} AND l.officers_id = ${officer} AND l.period_id = '${period}' AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.center_id= ${center} AND lw.officers_id = ${officer} AND lw.period_id = '${period}' AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.period_id = '${period}' AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.period_id = '${period}' AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.officers_id = ${officer} AND l.period_id = '${period}' AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.officers_id = ${officer} AND lw.period_id = '${period}' AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period != null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.center_id= ${center} AND l.period_id = '${period}' AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.center_id= ${center} AND lw.period_id = '${period}' AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.period_id = '${period}' AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.period_id = '${period}' AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.officers_id = ${officer} AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.officers_id = ${officer} AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, field_name, center_name, period_name, officer, loanRec, interestRec, depositRec, depositWithdrawal, total, date FROM (SELECT c.name, l.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, l.loan as loanRec, l.interest as interestRec, l.deposit as depositRec, 0 as depositWithdrawal, l.loan + l.interest + l.deposit AS total, created_at_date AS date FROM loan_collections AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.feild_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id = l.officers_id WHERE l.feild_id = ${field} AND l.officers_id = ${officer} AND DATE_FORMAT(l.created_at_date, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, lw.book, f.field_name, cn.center_name, p.period_name, u.name AS officer, 0 as loanRec, 0 as interestRec, 0 as depositRec, lw.withdrawal as depositWithdrawal, 0 AS total, lw.created_at AS date FROM loan_savings_withdrawals AS lw INNER JOIN client_registers AS c ON c.client_id = lw.client_id INNER JOIN feilds AS f ON f.feild_id = lw.feild_id INNER JOIN centers AS cn ON cn.center_id = lw.center_id INNER JOIN periods AS p ON p.period_id = lw.period_id INNER JOIN users AS u ON u.id = lw.officers_id WHERE lw.feild_id = ${field} AND lw.officers_id = ${officer} AND DATE_FORMAT(lw.created_at, '%Y-%m-%d') BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
}
// echo json_encode($query);
// die();
$result = $collection->incomeExpanceRecordload($query);
if ($result != false && $result != null) {
    // print_r($result);
    // die();
    $i = 1;
    foreach ($result as $keys => $value) {
        $subarray = array();
        $subarray[] = $i++;
        $subarray[] = date("d-m-Y", strtotime($value['date']));
        $subarray[] = $value['name'];
        $subarray[] = $value['book'];
        $subarray[] = $value['field_name'];
        $subarray[] = $value['center_name'];
        $subarray[] = $value['period_name'];
        $subarray[] = $value['depositRec'];
        $subarray[] = $value['loanRec'];
        $subarray[] = $value['interestRec'];
        $subarray[] = $value['total'];
        $subarray[] = $value['depositWithdrawal'];
        $subarray[] = $value['officer'];

        $output[] = $subarray;
    }
    $data = array(
        // "recordsFiltered" => $rowCount,
        "data" => $output,
    );
    echo json_encode($data);
} else {
    echo json_encode(null);
}
