<?php

use controller\CollectionController\CollectionController\CollectionController;

include_once "../controller/CollectionController.php";
// session_start();

$collection = new CollectionController();

$from_date = date("Y-m-d", strtotime($_POST['from_date']));
$end_date = date("Y-m-d", strtotime($_POST['end_date']));
$field = $_POST['field'];
$center = $_POST['center'];
$period = $_POST['period'];
$officer = $_POST['officer'];

if ($field == null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.reg_officer_id = '${officer}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.reg_officer_id = '${officer}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.reg_officer_id = '${officer}' AND l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.center_id = '${center}' AND l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.period_id = '${period}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.period_id = '${period}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.reg_officer_id = '${officer}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.reg_officer_id = '${officer}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,total_loan,interest,total_interest, officer, date FROM( SELECT c.name, l.book, 'ঋণ নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.created_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN  feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.reg_officer_id = '${officer}' AND l.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, l.book, 'ঋণ ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, l.total_loan, l.interest, l.total_interest, u.name AS officer, l.closing_at AS date FROM loan_profiles AS l INNER JOIN client_registers AS c ON c.client_id = l.client_id INNER JOIN feilds AS f ON f.feild_id = l.field_id INNER JOIN centers AS cn ON cn.center_id = l.center_id INNER JOIN periods AS p ON p.period_id = l.period_id INNER JOIN users AS u ON u.id =l.reg_officer_id WHERE l.field_id = '${field}' AND l.reg_officer_id = '${officer}' AND l.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
}
// echo json_encode($query);
// die();
$result = $collection->incomeExpanceRecordload($query);
if ($result != false && $result != null) {
    // print_r($result);
    // die();
    $i = 1;
    foreach ($result as $keys => $value) {
        $subarray = array();
        $subarray[] = $i++;
        $subarray[] = date("d-m-Y", strtotime($value['date']));
        $subarray[] = $value['name'];
        $subarray[] = $value['book'];
        $subarray[] = $value['type'];
        $subarray[] = $value['field_name'];
        $subarray[] = $value['center_name'];
        $subarray[] = $value['period_name'];
        $subarray[] = $value['total_loan'];
        $subarray[] = $value['interest'];
        $subarray[] = $value['total_interest'];
        $subarray[] = $value['officer'];

        $output[] = $subarray;
    }
    $data = array(
        // "recordsFiltered" => $rowCount,
        "data" => $output,
    );
    echo json_encode($data);
} else {
    echo json_encode(null);
}
