<?php

use controller\CollectionController\CollectionController\CollectionController;

include_once "../controller/CollectionController.php";
// session_start();

$collection = new CollectionController();

$from_date = date("Y-m-d", strtotime($_POST['from_date']));
$end_date = date("Y-m-d", strtotime($_POST['end_date']));
$field = $_POST['field'];
$center = $_POST['center'];
$period = $_POST['period'];
$officer = $_POST['officer'];

if ($field == null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.reg_officer_id = '${officer}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.reg_officer_id = '${officer}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.reg_officer_id = '${officer}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center != null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.center_id = '${center}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer == null && $period != null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.period_id = '${period}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.period_id = '${period}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field == null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.reg_officer_id = '${officer}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
} elseif ($field != null && $center == null && $officer != null && $period == null) {

    $query = "SELECT name, book, type, field_name, center_name, period_name,deposit_installment,interest, officer, date FROM( SELECT c.name, s.book, 'সঞ্চয় নিবন্ধন' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN  feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.reg_officer_id = '${officer}' AND s.created_at BETWEEN '${from_date}' AND '${end_date}' UNION ALL SELECT c.name, s.book, 'সঞ্চয় ক্লোজিং' AS type, f.field_name, cn.center_name, p.period_name, s.deposit_installment, s.interest, u.name AS officer, s.created_at AS date FROM saving_profiles AS s INNER JOIN client_registers AS c ON c.client_id = s.client_id INNER JOIN feilds AS f ON f.feild_id = s.field_id INNER JOIN centers AS cn ON cn.center_id = s.center_id INNER JOIN periods AS p ON p.period_id = s.period_id INNER JOIN users AS u ON u.id =s.reg_officer_id WHERE s.field_id = '${field}' AND s.reg_officer_id = '${officer}' AND s.closing_at BETWEEN '${from_date}' AND '${end_date}') AS a ORDER BY date DESC";
}
// echo json_encode($query);
// die();
$result = $collection->incomeExpanceRecordload($query);
if ($result != false && $result != null) {
    // print_r($result);
    // die();
    $i = 1;
    foreach ($result as $keys => $value) {
        $subarray = array();
        $subarray[] = $i++;
        $subarray[] = date("d-m-Y", strtotime($value['date']));
        $subarray[] = $value['name'];
        $subarray[] = $value['book'];
        $subarray[] = $value['type'];
        $subarray[] = $value['field_name'];
        $subarray[] = $value['center_name'];
        $subarray[] = $value['period_name'];
        $subarray[] = $value['deposit_installment'];
        $subarray[] = $value['interest'];
        $subarray[] = $value['officer'];

        $output[] = $subarray;
    }
    $data = array(
        // "recordsFiltered" => $rowCount,
        "data" => $output,
    );
    echo json_encode($data);
} else {
    echo json_encode(null);
}
